---
title: "Untitled"
author: "Charlene.Cheng"
date: "2/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# Load data
data(iris)
head(iris, 3)
```

```{r}
# log transform 
ir <- iris[, 1:4]
ir.species <- iris[, 5]
 
# apply PCA - scale. = TRUE is highly 
# advisable, but default is FALSE. 
ir.pca <- prcomp(ir,
                 center = TRUE,
                 scale. = TRUE) 
# print method
print(ir.pca)
# plot method
plot(ir.pca, type = "l")
# summary method
summary(ir.pca)
```
```{r}
# Predict PCs
predict(ir.pca, 
        newdata=tail(log.ir, 2))
```

```{r}
#Use R
ir.scaled <- scale(ir, center = TRUE, scale = TRUE)
# 1. Correlation matrix
res.cor <- cor(ir.scaled)
round(res.cor, 2)
# 2. Calculate eigenvectors/eigenvalues
res.eig <- eigen(res.cor)
res.eig
# 3. Calculate Propotion
res.eig$values/(sum(res.eig$values))
```
```{r}
#Use S
# 1. Covariance matrix
res.cov <- cov(ir.scaled)
# 2. Calculate eigenvectors/eigenvalues
eigen(res.cov)
# 3. Calculate Propotion
res.eig$values/(sum(res.eig$values))
```